# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
- master

pr:
- master

jobs:
- template: buildsystem/templates/windows.yml
  parameters:
    arch: 'x86'
- template: buildsystem/templates/windows.yml
  parameters:
    arch: 'x64'
- template: buildsystem/templates/windows.yml
  parameters:
    arch: 'arm'
- template: buildsystem/templates/windows.yml
  parameters:
    arch: 'arm64'
- template: buildsystem/templates/linux.yml
  parameters:
    arch: 'x86'
- template: buildsystem/templates/linux.yml
  parameters:
    arch: 'x64'
- template: buildsystem/templates/linux.yml
  parameters:
    arch: 'arm'
- template: buildsystem/templates/linux.yml
  parameters:
    arch: 'arm64'